### ISSUE TITLE
inconsistent results from the tutorial 

### ISSUE THREAD

**Issue by flyree** [yaleqc/qtcodes#70]
Hi all,

I am new to to qec code and I apologize for any inconvenience .

I was running the tutorial of XXZZ benchmark, but what I got was different than the figures showed in the tutorial.
[surface_perf1.pdf](https://github.com/yaleqc/qtcodes/files/7667481/surface_perf1.pdf)
[surface_perf2.pdf](https://github.com/yaleqc/qtcodes/files/7667484/surface_perf2.pdf)

I have checked the d_3_T_1.npz and make sure it is loaded by TopologicalBenchmark. The results remain the same. 

Thanks for the help!

**Comment by Phionx** [comment]
Thanks for opening this issue!

This is because of a relatively recent change in how Qiskit optimizes circuits. Currently, we are inserting noisy identity gates in places where we want to simulate inserting errors. However, now Qiskit optimizes the circuit and removes those identity gates, so that no errors are actually inserted in circuit simulations. We are aware of this and have a fix in the works!

Related to and tracked by #62, so closing this issue.
