### ISSUE TITLE
[Tutorial] Zero logical errors when running benchmarking

### ISSUE THREAD

**Issue by ronf6co** [yaleqc/qtcodes#78]
Hi,
I am trying to debug to understand why, but, when running https://github.com/yaleqc/qtcodes/blob/master/tutorials/xxzz/3-benchmarking.ipynb as is, it is not showing the same results - actually, it is not finding any logical errors.

![image](https://user-images.githubusercontent.com/13406570/150089019-bc53f39a-0b22-48cc-8fe5-8b4dccf05bd3.png)

![image](https://user-images.githubusercontent.com/13406570/150089066-211a8819-0860-4922-baab-07098036e5db.png)

**Comment by ronf6co** [comment]
While debugging I noticed that the syndrome is staying the same between 2 stabilizations that have noise addition with I between them. Same happened for 2 round of stabilize, or 4 rounds of stabilize:
![image](https://user-images.githubusercontent.com/13406570/150126419-37b7cf63-5989-4433-b619-4f70576b8656.png)
![image](https://user-images.githubusercontent.com/13406570/150126453-36ffd7d0-9834-4d94-a143-bb0642cca2c5.png)

**Comment by ronf6co** [comment]
it seems it is happening only when the NoiseModel is applied on id gate. other gates do not have these problem

**Comment by ronf6co** [comment]
The solution is optimization_level=0 which will not remove id gated for optimization
results = (execute(qc,Aer.get_backend("aer_simulator"),noise_model=get_noise_model(0.2),optimization_level=0,shots=2048).result().get_counts())

**Comment by Phionx** [comment]
Hi @ronf6co , 

Thanks for this issue, and apologies on the delayed response!

Yes, the issue (as you pointed out) was that Qiskit began to optimize away identity gates. These identity gates are used to insert errors in very particular places for the purposes of benchmarking. 

This issue is already being tracked in #62 , and should already be resolved in most parts of the codebase (e.g. [benchmarking.py](https://github.com/yaleqc/qtcodes/blob/master/qtcodes/tools/benchmarking.py#L107)). However, there may be some Jupyter notebook examples left to update. 

Are you using `qtcodes-0.1.0`?

We are aiming to publish `qtcodes-0.2.0` soon. Until then, I'd recommend building from source as per: https://github.com/yaleqc/qtcodes#building-from-source.
